name: py5hybrid
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cairo
  - cairosvg
  - jpype1
  - jupyterlab
  - line_profiler
  - matplotlib
  # - maven  # don't install maven through Anaconda!
  - numpy
  - pillow
  - pip
  - scikit-learn
  - pip:
      - py5[jupyter]
